spring:
  profiles:
    active:
    - dev

---
server:
  port: 8001
spring:
  profiles: dev
  application:
    name: microservice-config-provider8001
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/microservice_provider?useSSL=false&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: 123456
#将本服务注册进eureka
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
      #,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    #主机映射名称
    instance-id: microservice-Provider-8001
    #访问路径显示IP
    prefer-ip-address: true

info:
  app.name: microservice
  company.name: 个人
  build.artifactId: $project.artifactId$
  build.version: $project.version$

---
server:
  port: 8001
spring:
  profiles: test
  application:
    name: microservice-config-provider8001
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/microservice_provider?useSSL=false&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: 123456
#将本服务注册进eureka
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    #主机映射名称
    instance-id: microservice-Provider-8001
    #访问路径显示IP
    prefer-ip-address: true

info:
  app.name: microservice
  company.name: 个人
  build.artifactId: $project.artifactId$
  build.version: $project.version$